spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profilelist
    username: postgres
    password: 1ktl2710zlA@
  jpa:
    database-platform: org.hibernate.dialect.PosgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000

# AWS S3 Configuration
aws:
  s3:
    bucket-name: your-contact-images-bucket
    region: us-east-1
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    endpoint: https://s3.amazonaws.com
  cloudfront:
    domain: ${CLOUDFRONT_DOMAIN:}

server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
